### ISSUE TITLE
Add an event for when a bot stops sending heartbeats

### ISSUE THREAD

**Issue by Hhanuska** [tf2-automatic/tf2-automatic#240]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Is your feature request related to a problem? Please describe.

Currently there is an event for when a bot disconnects from Steam, but there isn't one when the bot is no longer available for communication.

### Describe the solution you'd like

Add an event that fires if a bot is no longer sending heartbeats. Opposite of the current BOT_READY_EVENT

### Describe alternatives you've considered

Alternative solution is waiting for a "Bot not found" error while trying to communicate with the bot

**Comment by zudsniper** [comment]
Would you set a timeout, perhaps via an environment variable, to determine when a bot has stopped sending heartbeats, and thus this event should be sent?

**Comment by zudsniper** [comment]
Or perhaps you want mean an event firing if the bot disconnects as expected, and therefore tells the system it is leaving. Or maybe both, with different messages emitted

**Comment by Hhanuska** [comment]
I think both should exist for sure, doesn't necessarily have to be different events.

**Comment by Nicklason** [comment]
@zudsniper Configurable heartbeat intervals was a good idea and I have implemented that now.

Regarding this issue, I think I will make the bot tell the manager what its heartbeat interval is together with the actual heartbeat. Then the manager can detect that the bot no longer works because the manager did not receive a heartbeat at the time it expected. The event will most likely be called something like "bot.stopped".
