### ISSUE TITLE
Manager refresh trade offers

### ISSUE THREAD

**Issue by Hhanuska** [tf2-automatic/tf2-automatic#350]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Is your feature request related to a problem? Please describe.

Trade offers may appear glitched (no items on either side), when Steam is experiencing issues. They may load properly if we try to reload them after Steam servers are back up.

### Describe the solution you'd like

Add a new option for creating trade jobs to the manager, with `type: 'REFRESH'`, which will attempt to refresh the trade offer until it is no longer glitched.

### Describe alternatives you've considered

The offer can be reloaded directly through the bot using `/trades/{id}`, but this task is better suited for the manager.

**Comment by Nicklason** [comment]
I have a few ideas:

- Do you think the manager should automatically create the refresh job when it sees a glitched offer?
- Should the manager emit trade offer states too? Instead of listening to the trade events from the bot, you could listen to the manager, which will make sure that the offer states you receive are not glitched? I think that would be neat, but it would also be unnecessary for people who do not want to use this functionality. Maybe it should be an environment variable for the bot manager to enable/disable this behavior?

**Comment by Hhanuska** [comment]
I don't think it should be automatic, some trades may just need to be accepted/declined (admin trade/sr banned etc.) regardless of the content. Or it could be automatic, but an event should still be emitted when the offer is received.

Not sure what you mean by the second point. `TRADE_RECEIVED_EVENT` already only emits active trades. Glitched offers will still have the same state, just it will appear as empty.
