### ISSUE TITLE
Offer being sent multiple times on a single http request

### ISSUE THREAD

**Issue by HavishH** [tf2-automatic/tf2-automatic#530]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Expected behavior

When calling the Create Trade Job endpoint, a single trade offer should be created.

### Actual behavior

Calling the endpoint a single time resulted in multiple trade offers being created, it seemed to be the result of a socket hang up.

### Steps to reproduce

1. Send a POST request to /trades on the 'bot-manager'
2. (Presumably) Lose connection to Steam while the job is being processed.

### TF2 Automatic version

8.0.0-dev.8

### Projects

- [X] @tf2-automatic/bot
- [X] @tf2-automatic/bot-manager
- [ ] @tf2-automatic/bot-data
- [ ] @tf2-automatic/bot-manager-data
- [ ] @tf2-automatic/bptf-manager
- [ ] @tf2-automatic/bptf-manager-data
- [ ] Other (see below)

**Comment by Nicklason** [comment]
This has been fixed in the dev branch. The bot now accepts a header called `X-Idempotency-Key` on all post requests. The token is a unique string provided by the client to ensure that multiple attempts at performing the same action is only handled once. The bot-manager uses the id of the trade job as an idempotency token when creating offers.

Some things to keep in mind when using idempotency tokens:

- Concurrent requests made using the same token will fail with status code 409 while the first request is still being processed.
- Results of requests are stored in memory for an hour and any retries using the same token will return the same result.
- HTTP responses with status code 4xx are not stored in memory.
- If the parameters (request path and body) of requests using the same token are different then the request will fail with status code 400.
